name: Meme Bot

on:
  push:

  pull_request:



jobs:
  build:
    env: 
      acc_key : ${{ secrets.acc_key }}
      acc_secret : ${{ secrets.acc_secret }}
      c_key : ${{ secrets.c_key }}
      c_secret : ${{ secrets.c_secret }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run unittest
      run: python -m unittest
